<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        Activity::insert([
            ['activity_name' => 'Coordination de la transition vers le nouveau programme Erasmus+'],
            ['activity_name' => 'Demandes de financements projets de mobilité'],
            ['activity_name' => 'Référente de la mobilité EUNICE'],
            ['activity_name' => 'Pilotage et planification des aspects administratifs et financiers de la mobilité internationale'],
            ['activity_name' => 'Développement de la mobilité internationale du personnel (entrants & sortants)'],
            ['activity_name' => 'Pilotage de la promotion de la mobilité étudiante entrante et sortante'],
            ['activity_name' => 'Liaison avec Direction de la Communication'],
            ['activity_name' => 'Mise à jour du site web et de l’ENT, référent DRUPAL du PRI'],
            ['activity_name' => 'Participation aux outputs des Projets'],
            ['activity_name' => 'Mise à jour et développement des accords de mobilité Erasmus+'],
            ['activity_name' => 'Maintien du contact partenaires Erasmus+ en lien avec les composantes de formation'],
            ['activity_name' => 'Saisie et mise à jour du logiciel de gestion MoveOn en lien avec les accords'],
            ['activity_name' => 'Gestion du budget « Soutien Organisationnel » Erasmus+'],
            ['activity_name' => 'Saisie de données sur Mobility Tool et Beneficiary Module'],
            ['activity_name' => 'Assistance à l\'élaboration des rapports qualitatifs et financiers des mobilités Erasmus+'],
            ['activity_name' => 'Réponses aux sollicitations des personnels sur la mobilité Erasmus+'],
            ['activity_name' => 'Gestion administrative et financière des mobilités de personnel'],
            ['activity_name' => 'Organisation de l\'accueil des mobilités entrantes du personnel/enseignants-chercheurs'],
            ['activity_name' => 'Actualisation de la documentation en lien avec le programme Erasmus+'],
            ['activity_name' => 'Organisation et participation à des événements pour la promotion de la mobilité'],
            ['activity_name' => 'Organisation et participation aux sorties culturelles'],
            ['activity_name' => 'Organisation et participation aux journées d\'intégration'],
            ['activity_name' => 'Gestion des réseaux sociaux RI'],
            ['activity_name' => 'Elaboration de documents d\'information et de promotion à l’International'],
            ['activity_name' => 'Elaboration d\'outils et événements de promotion de la mobilité internationale étudiante'],
            ['activity_name' => 'Valorisation des activités du PRI en interne et en externe'],
            ['activity_name' => 'Participation à la communication des projets du portefeuille PRI'],
            ['activity_name' => 'Participation à des réunions de référents (différentes thématiques)'],
            ['activity_name' => 'Suivi des installations techniques et des matériels'],
            ['activity_name' => 'Vérification de l\'état des espaces publics et internes : fuites, propreté, sobriété énergétique'],
            ['activity_name' => 'Gestion des interventions en lien avec les services techniques'],
            ['activity_name' => 'Assurer le suivi et la mise à jour de la signalétique dans les espaces'],
            ['activity_name' => 'Participation aux réaménagements de salles et changement de mobilier du PRI'],
            ['activity_name' => 'Suivi du stock des documents de communication'],
            ['activity_name' => 'Recherche et achat des goodies'],
            ['activity_name' => 'Suivi du stock des goodies'],
            ['activity_name' => 'Suivi du tri des déchets pour les locaux du PRI'],
            ['activity_name' => 'Assistance à la préparation du budget du PRI et en suivre l\'exécution'],
            ['activity_name' => 'Demandes de création de fournisseurs'],
            ['activity_name' => 'Demandes de devis auprès des fournisseurs'],
            ['activity_name' => 'Demandes d\'achat'],
            ['activity_name' => 'Attestations de service fait'],
            ['activity_name' => 'Réception des marchandises'],
            ['activity_name' => 'Suivi budgétaire PRI'],
            ['activity_name' => 'Accompagnement à l\'établissement des demandes de BR'],
            ['activity_name' => 'Rédaction de l\'analyse financière budget PRI'],
            ['activity_name' => 'Réservation des billets de train des agents'],
            ['activity_name' => 'Réservation des hôtels des agents et chargés de missions'],
            ['activity_name' => 'Réservation des restaurants pour événements'],
            ['activity_name' => 'Réception des justificatifs pour les missions'],
            ['activity_name' => 'Accompagnement au recrutement des contrats étudiants'],
            ['activity_name' => 'Réception et tri du courrier'],
            ['activity_name' => 'Classification et archive des documents administratifs et financiers'],
            ['activity_name' => 'Commandes de fourniture au magasin général UPHF et gestion des stocks'],
            ['activity_name' => 'Réalisation de l\'accueil physique et l\'accueil téléphonique'],
            ['activity_name' => 'Gestion de la logistique pour les réunions'],
            ['activity_name' => 'Courses pour les événements organisés au PRI'],
            ['activity_name' => 'Recensement des besoins à l\'année en heures des étudiants contrat région en accueil et informatique et assurer un suivi fin de la consommation à des fins de prospective'],
            ['activity_name' => 'Relevé des heures effectuées par les étudiants contrat région en accueil et informatique'],
            ['activity_name' => 'Demandes, réception des contrats étudiants et suivi des signatures avec la DRH'],
            ['activity_name' => 'Suivi des états de paiement des contractuels étudiants'],
            ['activity_name' => 'Tri des archives administratives, en lien avec le service des archives'],
            ['activity_name' => 'Gestion administrative des bourses Eiffel'],
            ['activity_name' => 'Accueil physique et accompagnement des étudiants étrangers conventionnés'],
            ['activity_name' => 'Accueil physique et accompagnement des étudiants sortants L M D UPHF et INSA'],
            ['activity_name' => 'Participation aux événements de l\'université et du PRI : Cap Campus, Forum Demo, ...'],
            ['activity_name' => 'Information sur les aspects financiers des mobilités sortantes'],
            ['activity_name' => 'Préparation des commissions d’attribution des financements de la mobilité internationale'],
            ['activity_name' => 'Gestion de la documentation liée à l’attribution des financements'],
            ['activity_name' => 'Promotion de la mobilité internationale et communication'],
            ['activity_name' => 'Mise à jour des documents de promotion, de Moodle et du site web IN et OUT'],
            ['activity_name' => 'Interface avec les partenaires extérieurs Ministère et Région quant aux financements de la mobilité internationale'],
            ['activity_name' => 'Envoi d\'un mailchimp aux partenaires'],
            ['activity_name' => 'Participation aux actions de promotions des partenaires'],
            ['activity_name' => 'Réception des nominations'],
            ['activity_name' => 'Envoi de la procédure de candidature aux étudiants nominés'],
            ['activity_name' => 'Traitement des candidatures'],
            ['activity_name' => 'Envoi des candidatures aux composantes'],
            ['activity_name' => 'Gestion de la demande de visa pour les étudiants conventionnés sur la plateforme Etudes en France'],
            ['activity_name' => 'Revue dossier inscription et process avec scolarité'],
            ['activity_name' => 'Envoi des dossiers d\'inscription et suivi des étudiants'],
            ['activity_name' => 'Vérification des dossiers d\'inscription et transmission à la scolarité centrale'],
            ['activity_name' => 'Envoi des lettres d\'acceptations'],
            ['activity_name' => 'Gestion d’un contingent de logements CROUS'],
            ['activity_name' => 'Gestion de la convention CROUS'],
            ['activity_name' => 'Organisation international academy'],
            ['activity_name' => 'Collecte des informations de rentrée des composantes'],
            ['activity_name' => 'Complétion des attestations d\'arrivée des étudiants Erasmus+'],
            ['activity_name' => 'Complétion des attestations de présence des étudiants Erasmus+'],
            ['activity_name' => 'Organisation d\'une session de préparation à l\'arrivée'],
            ['activity_name' => 'Réception des contrats pédagogiques et transmissions aux composantes'],
            ['activity_name' => 'Renvoi des avenants aux composantes si PRI destinataire'],
            ['activity_name' => 'Récolte des notes du semestre'],
            ['activity_name' => 'Edition des Relevés de notes'],
            ['activity_name' => 'Mise en place calendrier promotionnel Etudes annuel (remontée par les composantes après sollicitation)'],
            ['activity_name' => 'Erasmus Days Préparation'],
            ['activity_name' => 'Erasmus Days Evénement'],
            ['activity_name' => 'MAJ des ppt promotionnels Pourquoi partir, Constituer son dossier, Canada'],
            ['activity_name' => 'MAJ info Canada (immigration, BCI, accords d\'échange)'],
            ['activity_name' => 'MAJ site web (financements, étapes…)'],
            ['activity_name' => 'MAJ des todolist Etudes et stages'],
            ['activity_name' => 'MAJ des documents financements: contrats de mobilité, contrats pédagogiques hors europe et SMT, formulaires allocations SMS SMT, attestation arrivée et présence'],
            ['activity_name' => 'Gestion des procédures et de leur suivi auprès des étudiants sortants UPHF et INSA'],
            ['activity_name' => 'Nomination auprès des partenaires'],
            ['activity_name' => 'Gestion plateforme BCI du programme PQEE'],
            ['activity_name' => 'Team JEKI formulaires publicateur back office moveon'],
            ['activity_name' => 'Gestion des mobilité dans moveon: fiches séjours, suivi et MAJ'],
            ['activity_name' => 'Edition contrats de mobilité'],
            ['activity_name' => 'Sessions préparation au départ pour les études et le stage'],
            ['activity_name' => 'Canada-Québec: Protocoles d\'entente RAMQ AMELI'],
            ['activity_name' => 'Récolter les lettres d\'admission ou courriels d\'admission'],
            ['activity_name' => 'Conseils et orientation des étudiants tout au long du processus'],
            ['activity_name' => 'Suivi des contrats pédagogiques et de leurs avenants et des OLA des étudiants LMD UPHF et INSA'],
            ['activity_name' => 'Récolter les relevés de notes des étudiants après la mobilité sortante'],
            ['activity_name' => 'Envoi attestation d\'arrivée aux étudiants'],
            ['activity_name' => 'Récolte attestations d\'arrivée'],
            ['activity_name' => 'Envoi attestation de présence aux étudiants'],
            ['activity_name' => 'Récolte attestations de présence d\'arrivée'],
            ['activity_name' => 'Rapport de mobilité E+: envoi message aux étudiants et action plateforme'],
            ['activity_name' => 'Reporting Mobility Tool'],
            ['activity_name' => 'Financements: national AMI bilan financier + enquête annuelle'],
            ['activity_name' => 'Financements: région MERMOZ bilan financier + enquête annuelle'],
            ['activity_name' => 'Prise de contact avec les universités et participer à la formalisation des accords BRIDGE'],
            ['activity_name' => 'Organisation des appels à candidatures pour les étudiants sortants et les stages entrants BRIDGE'],
            ['activity_name' => 'Organisation des réunions d\'informations auprès des enseignants-chercheurs et/ou d\'étudiants BRIDGE'],
            ['activity_name' => 'Accueil des stagiaires entrants BRIDGE'],
            ['activity_name' => 'Organisation et planification des formations MoveOn pour les utilisateurs en lien avec les référents MoveOn de l’établissement'],
            ['activity_name' => 'Suivi les actualités et les nouvelles fonctionnalités MoveOn'],
            ['activity_name' => 'Organisation des réunions avec les utilisateurs MoveOn'],
            ['activity_name' => 'Paramétrage de la base Moveon INSA HdF en fonction des besoins'],
            ['activity_name' => 'Encadrement de contrat région dont les missions sont reliées à MoveOn'],
            ['activity_name' => 'Faire le lien entre le support et la base MoveOn INSA'],
            ['activity_name' => 'Production de documentation pour aider les utilisateurs Moveon'],
            ['activity_name' => 'Contribution à la sous-équipe PRI en charge du développement et des problématiques liées à MoveOn'],
            ['activity_name' => 'Suivi la ligne budgétaire du soutien organisationnel KA131 INSA'],
            ['activity_name' => 'Déclaration des mobilités sur le Beneficiary Module KA131 INSA'],
            ['activity_name' => 'Rédaction des rapports intermédiaires et finaux KA131 INSA'],
            ['activity_name' => 'Représentation de l’université lors de rencontres avec des partenaires et des bailleurs'],
            ['activity_name' => 'Conseils aux porteurs de projets dans la définition et l’écriture de projets en lien avec le Royaume-Uni'],
            ['activity_name' => 'Faire la liaison avec la Cellule Mobilité sur les partenariats comprenant des volets de mobilité'],
            ['activity_name' => 'Développement et le suivi des partenariats, principalement hors Europe'],
            ['activity_name' => 'Pilotage des activités d’animation et de communication du PRI pour sensibiliser aux questions de coopération internationale'],
            ['activity_name' => 'Faire le montage et le suivi des accords de collaboration avec les universités partenaires hors Europe'],
            ['activity_name' => 'Contribution au développement de nouveaux modèles de partenariat pour des coopérations innovantes, en cohérence avec la politique de l\'établissement'],
            ['activity_name' => 'Conseil aux porteurs de projets dans la définition et l’écriture de projets européens et internationaux'],
            ['activity_name' => 'Participation à l\'exécution des projets en gestion au PRI : IUMEME'],
            ['activity_name' => 'Participation à l\'exécution des projets en gestion au PRI : EFEU'],
            ['activity_name' => 'Participation à l\'exécution des projets en gestion au PRI : SCALENEO'],
            ['activity_name' => 'Participation à l\'exécution des projets en gestion au PRI : EUNICE4U'],
            ['activity_name' => 'Création de documents visant à améliorer la productivité du PRI'],
            ['activity_name' => 'Intervention ponctuellement sur tout type de projet en soutien'],
            ['activity_name' => 'Coordination du projet : IUMEME'],
            ['activity_name' => 'Accompagnement des doctorants et enseignants-chercheurs étrangers pour toutes questions d’ordre administratif et pratique relatives à la préparation de leur séjour et de leur installation à Valenciennes EURAXESS'],
            ['activity_name' => 'Travail en étroite collaboration avec l’OFII et la Préfecture pour les demandes de titres de séjour EURAXESS'],
            ['activity_name' => 'Coordination des activités du projet EUNICE4U à l’UPHF et au niveau de la Project Management Team de l’alliance EUNICE'],
            ['activity_name' => 'Coordination des acteurs et des comités du projet en interne : cellule EUNICE, groupes opérationnels, comité de qualité, comités de conseil et de pilotage, etc.'],
            ['activity_name' => 'Mise en oeuvre et suivi des indicateurs en lien avec le pilote du projet EUNICE au sein de l’UPHF'],
            ['activity_name' => 'Participation à la rédaction des livrables et des rapports d’activité trimestriels, à leur vérification et dépôt'],
            ['activity_name' => 'Transmettre les sollicitations du personnel et des étudiants concernant les opportunités EUNICE'],
            ['activity_name' => 'Soutien autres groupes de travail du projet EUNICE4U'],
            ['activity_name' => 'Participation à l’organisation d’événements à l’UPHF'],
            ['activity_name' => 'Co-organisation de la semaine internationale de l\'IAE'],
            ['activity_name' => 'Organisation d\'activités et programmes visant à l’accompagnement des publics EURAXESS'],
            ['activity_name' => 'Participation aux événements et groupes de travail mis en place par EURAXESS France'],
            ['activity_name' => 'Mise en place d\'une communication relative au Centre EURAXESS de l’UPHF'],
            ['activity_name' => 'Accompagnement des doctorants et enseignants-chercheurs étrangers']
        ]);
    }
}
